//HintName: Pages.TestWithParamatersPage.g.cs
// <auto-generated />
#nullable enable

public static partial class Pages
{
    /// <summary>
    /// Route: <c>/test-with-parameters/{id:int}/{name}</c>
    /// </summary>
    public static string TestWithParamaters(int id, string name)
    {
        return $"/test-with-parameters/{id}/{name}";
    }
}
