name: conventional-commits

on:
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: webiny/action-conventional-commits@v1.1.0
